config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

	resources :exposes do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :taos do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :tao_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :kus do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :ku_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :pics do
		member do
			put "like", to: "pics#upvote"
			put "dislike", to: "pics#downvote"
			put :publish
			put :unpublish
		end
		get :list, on: :collection
	end
end

app/models/ku.rb
class Ku < ApplicationRecord
	belongs_to :user
	belongs_to :ku_category, foreign_key: "category_id"

	scope :published, -> { where published: true }
end

app/controllers/kus_controller.rb
class KusController < ApplicationController

	def index
		@kus = Ku.published.order(id: :desc)
	end

	def new
		@ku = Ku.new
		@ku_category = KuCategory.new
	end

	def create
		@ku = Ku.new(ku_params)
		@ku.user_id = current_user.id
		@ku.save
		redirect_to @ku
	end

	def show
		@ku = Ku.find(params[:id])
	end

	def list
		@kus = Ku.all.order(id: :desc)
	end

	def edit
		@ku = Ku.find(params[:id])
		@ku_category = KuCategory.new
	end

	def update
		@ku = Ku.find(params[:id])
		@ku.update(ku_params)
		redirect_to @ku
	end

	def publish
		@record = Ku.find(params[:id])
		@record.update_attributes(published: true)
		@record.reload
		render "common/publish"
	end

	def unpublish
		@record = Ku.find(params[:id])
		@record.update_attributes(published: false)
		@record.reload
		render "common/publish"
	end

	def destroy
		@ku = Ku.find(params[:id])
		@ku.destroy
		redirect_to list_kus_path
	end

	private
	def ku_params
		params.require(:ku).permit(:category_id, :title, :title, :desc, :content, :user_id, :position, :published)
	end
end

app/views/kus/edit.html.erb
<%= form_for @ku ,method: :put, html: {class: 'form-horizontal', multipart: true} do |f|%>
	<div class="form-group">
		<%= f.label :category_id, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.collection_select :category_id, KuCategory.arrange_as_array({order: 'title'}, @ku_category.possible_parents) , :id, :name_for_selects, include_blank: true, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :title, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_field :title, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :desc, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :desc, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :content, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :content, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :position, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :position, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/kus/index.html.erb
<div class="container">
	<div class="row">
		<% @kus.each do |t| %>
			<div class="col-sm-6 col-md-4 col-lg-4 mt-4">
				<div class="card">
					<%= image_tag '', class: "card-img-top"%>
					<div class="card-block">
						<h4 class="card-title"><%= t.title %></h4>
						<!-- <div class="meta"><a href="#">玩物</a></div> -->
						<div class="card-text">
							<%= t.desc %>
						</div>
					</div>
					<div class="card-footer">
						<span class="float-right">bb</span>
						<span style="color:#F00">aa</span>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/kus/list.html.erb
<h1>
	猴子库
	<%= link_to '创建猴子库', new_ku_path, target: "_blank", class: "btn btn-primary float-right", role: "button" %>
</h1>

<table class="table table-hover">
	<thead>
		<tr class="table-secondary">
			<th>ID</th>
			<th>分类</th>
			<th>标题</th>
			<th>简介</th>
			<th>创建时间</th>
			<th>权重</th>
			<th>发布？</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @kus.each do |t| %>
			<tr>
				<th scope="row"><%= t.id %></th>
				<td><%= link_to t.ku_category.title, ku_category_path(t.ku_category), target: "_blank" %></td>
				<td><%= link_to t.title, t, target: "_blank" %></td>
				<td><%= t.desc %></td>
				<td>
					<%= link_to t.user.name, user_path(t.user), target: "_blank" %><br />
					<span class='small' ><%= t.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
				</td>
				<td><%= t.position %></td>
				<td><%= render partial:'common/publish', locals:{record: t} %></td>
				<td>
					<%= link_to '查看', t, target: "_blank" %>
					<%= link_to '编辑', edit_ku_path(t), target: "_blank" %>
					<%= link_to '删除', t, method: :delete, data: { confirm: 'Are you sure?' } %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/kus/new.html.erb
<%= form_for @ku ,method: :post, html: {class: 'form-horizontal', multipart: true} do |f|%>
	<div class="form-group">
		<%= f.label :category_id, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.collection_select :category_id, KuCategory.arrange_as_array({order: 'title'}, @ku_category.possible_parents) , :id, :name_for_selects, include_blank: true, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :title, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_field :title, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :desc, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :desc, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :content, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :content, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :position, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :position, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/kus/show.html.erb
<p>
  <strong>title:</strong>
  <%= @ku.title %>
</p>

<p>
  <strong>desc:</strong>
  <%= @ku.desc %>
</p>

<p>
  <strong>user_id:</strong>
  <%= @ku.user_id %>
</p>