config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

	resources :exposes do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :taos do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :tao_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :kus do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :ku_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :pics do
		member do
			put "like", to: "pics#upvote"
			put "dislike", to: "pics#downvote"
			put :publish
			put :unpublish
		end
		get :list, on: :collection
	end
end

app/models/pic.rb
class Pic < ApplicationRecord
	acts_as_votable
	belongs_to :user

	has_attached_file :media, styles: { large: '800x800>', middle: '300x300>', small: '100x100>' }
	validates_attachment_content_type :media, content_type: %w[image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif]

	scope :published, -> { where published: true }
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		@pics = Pic.published.order(position: :desc)
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = Pic.new(pic_params)
		@pic.user_id = current_user.id
		@pic.save
		redirect_to @pic
	end

	def show
		@pic = Pic.find(params[:id])
	end

	def list
		@pics = Pic.all.order(id: :desc)
	end

	def upvote
		@pic = Pic.find(params[:id])
		@pic.upvote_by current_user
		redirect_to @pic
	end

	def downvote
		@pic = Pic.find(params[:id])
		@pic.downvote_by current_user
		redirect_to @pic
	end

	def edit
		@pic = Pic.find(params[:id])
	end

	def update
		@pic = Pic.find(params[:id])
		@pic.update(pic_params)
		redirect_to @pic
	end

	def publish
		@record = Pic.find(params[:id])
		@record.update_attributes(published: true)
		@record.reload
		render "common/publish"
	end

	def unpublish
		@record = Pic.find(params[:id])
		@record.update_attributes(published: false)
		@record.reload
		render "common/publish"
	end

	def destroy
		@pic = Pic.find(params[:id])
		@pic.destroy
		redirect_to list_pics_path
	end

	private
	def pic_params
		params.require(:pic).permit(:desc, :media, :user_id, :position, :published)
	end
end

app/views/pics/edit.html.erb
<%= form_for @pic ,method: :put, html: {class: 'form-horizontal', multipart: true} do |f|%>
	<div class="form-group">
		<%= f.label :desc, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :desc, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :media, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.file_field :media, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :position, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :position, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/pics/index.html.erb
<div class="container">
	<div class="row">
		<% @pics.each do |t| %>
			<div class="col-sm-6 col-md-4 col-lg-4 mt-4">
				<div class="card">
					<%= image_tag t.media.url(:large), class: "card-img-top"%>
					<div class="card-block">
						<h4 class="card-title"><%= link_to t.desc, pic_path(t) %></h4>
						<!-- <div class="meta"><a href="#">玩物</a></div> -->
						<!-- <div class="card-text">
							<%= t.desc %>
						</div> -->
					</div>
					<div class="card-footer">
						<span class="float-right"><%= t.user.name %></span>
						<span style="color:#F00">bb</span>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

<%= link_to '提交图片', new_pic_path %>

app/views/pics/list.html.erb
<h1>
	猴子图
	<%= link_to '创建猴子图', new_pic_path, target: "_blank", class: "btn btn-primary float-right", role: "button" %>
</h1>

<table class="table table-hover">
	<thead>
		<tr class="table-secondary">
			<th>ID</th>
			<th>图片</th>
			<th>标题</th>
			<th>创建时间</th>
			<th>权重</th>
			<th>发布？</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @pics.each do |t| %>
			<tr>
				<th scope="row"><%= t.id %></th>
				<td>
					<%= link_to t, target: "_blank" do %>
						<%= image_tag t.media.url(:small), size: "60x60" %>
					<% end %>
				</td>
				<td><%= link_to t.desc, t, target: "_blank" %></td>
				<td>
					<%= link_to t.user.name, user_path(t.user), target: "_blank" %><br />
					<span class='small' ><%= t.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
				</td>
				<td><%= t.position %></td>
				<td><%= render partial:'common/publish', locals:{record: t} %></td>
				<td>
					<%= link_to '查看', t, target: "_blank" %>
					<%= link_to '编辑', edit_pic_path(t), target: "_blank" %>
					<%= link_to '删除', t, method: :delete, data: { confirm: 'Are you sure?' } %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/pics/new.html.erb
<%= form_for @pic ,method: :post, html: {class: 'form-horizontal', multipart: true} do |f|%>
	<div class="form-group">
		<%= f.label :desc, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :desc, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :media, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.file_field :media, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/pics/show.html.erb
<p>
  <strong>desc:</strong>
  <%= @pic.desc %>
</p>

<p>
  <strong>user_id:</strong>
  <%= @pic.user_id %>
</p>

<%= image_tag @pic.media.url(:small) %>

<br/>
<%=link_to like_pic_path(@pic), method: :put, class: 'btn btn-default btn-sm' do %>
	<span class="glyphicon glyphicon-chevron-up"></span>
	like <%=@pic.get_upvotes.size%></td>
<% end %>
<%=link_to dislike_pic_path(@pic), method: :put, class: 'btn btn-default btn-sm' do %>
	<span class="glyphicon glyphicon-chevron-down"></span>
	dislike <%=@pic.get_downvotes.size%></td>
<%end%>