config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

	resources :exposes do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :taos do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :tao_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :kus do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :ku_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :pics do
		member do
			put "like", to: "pics#upvote"
			put "dislike", to: "pics#downvote"
			put :publish
			put :unpublish
		end
		get :list, on: :collection
	end
end

app/models/tao.rb
class Tao < ApplicationRecord
	belongs_to :user
	belongs_to :tao_category, foreign_key: "category_id"

	has_attached_file :pic, styles: { large: '800x800>', middle: '300x300>', small: '100x100>' }
	validates_attachment_content_type :pic, content_type: %w[image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif]

	scope :published, -> { where published: true }
end

app/controllers/taos_controller.rb
class TaosController < ApplicationController

	def index
		@taos = Tao.published.order(position: :desc)
	end

	def new
		@tao = Tao.new
		@tao_category = TaoCategory.new
	end

	def create
		@tao = Tao.new(tao_params)
		@tao.user_id = current_user.id
		@tao.expose_id = current_user.id if tao_params["user_id"].blank?
		@tao.save
		redirect_to @tao
	end

	def edit
		@tao = Tao.find(params[:id])
		@tao_category = TaoCategory.new
	end

	def update
		@tao = Tao.find(params[:id])
		@tao.update(tao_params)
		redirect_to @tao
	end

	def show
		@tao = Tao.find(params[:id])
	end

	def list
		@taos = Tao.all.order(id: :desc)
	end

	def publish
		@record = Tao.find(params[:id])
		@record.update_attributes(published: true)
		@record.reload
		render "common/publish"
	end

	def unpublish
		@record = Tao.find(params[:id])
		@record.update_attributes(published: false)
		@record.reload
		render "common/publish"
	end

	def destroy
		@tao = Tao.find(params[:id])
		@tao.destroy
		redirect_to list_taos_path
	end

	private
	def tao_params
		params.require(:tao).permit(:category_id, :title, :price, :baoyou, :pic, :url, :fanli_url, :title, :desc, :content, :user_id, :expose_id, :position, :published)
	end
end

app/views/taos/edit.html.erb
<%= form_for @tao ,method: :put, html: {class: 'form-horizontal', multipart: true} do |f|%>
	<div class="form-group">
		<%= f.label :category_id, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.collection_select :category_id, TaoCategory.arrange_as_array({order: 'title'}, @tao_category.possible_parents) , :id, :name_for_selects, include_blank: true, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :title, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_field :title, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :price, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :price, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :baoyou, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.check_box :baoyou, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :pic, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.file_field :pic, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :url, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :url, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :fanli_url, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :fanli_url, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :desc, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :desc, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :content, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :content, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :expose_id, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :expose_id, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :position, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :position, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/taos/index.html.erb
<div class="container">
	<div class="row">
		<% @taos.each do |t| %>
			<div class="col-sm-6 col-md-4 col-lg-4 mt-4">
				<div class="card">
					<%= link_to tao_path(t), target: "_blank" do %>
						<%= image_tag t.pic.url(:large), class: "card-img-top" %>
					<% end %>
					<div class="card-block">
						<h4 class="card-title"><%= link_to t.title, tao_path(t), target: "_blank" %></h4>
						<!-- <div class="meta"><a href="#">玩物</a></div> -->
						<div class="card-text">
							<%= t.desc %>
						</div>
					</div>
					<div class="card-footer">
						<span class="float-right"><%= link_to '去购买>', t.fanli_url, target: "_blank" %></span>
						<span style="color:#F00"><%= t.price %>元<%= t.baoyou == true ? "（包邮）" : "" %></span>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/taos/list.html.erb
<h1>
	猴子淘
	<%= link_to '创建猴子淘', new_tao_path, target: "_blank", class: "btn btn-primary float-right", role: "button" %>
</h1>

<table class="table table-hover">
	<thead>
		<tr class="table-secondary">
			<th>ID</th>
			<th>分类</th>
			<th>图片</th>
			<th>标题</th>
			<th>价格</th>
			<th>创建时间</th>
			<th>权重</th>
			<th>发布？</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @taos.each do |t| %>
			<tr>
				<th scope="row"><%= t.id %></th>
				<td><%= link_to t.tao_category.title, tao_category_path(t.tao_category), target: "_blank" %></td>
				<td>
					<%= link_to t, target: "_blank" do %>
						<%= image_tag t.pic.url(:small), size: "60x60" %>
					<% end %>
				</td>
				<td>
					<%= link_to t.title, t, target: "_blank" %><br />
					<span class='small' ><%= t.desc %></span>
				</td>
				<td>
					<%= t.price %>元<%= t.baoyou == true ? "（包邮）" : "" %><br />
					<%= link_to '返', t.fanli_url, target: "_blank", class: "btn btn-outline-primary btn-sm", role: "button" %>
					<%= link_to '真', t.url, target: "_blank", class: "btn btn-outline-warning btn-sm", role: "button" %>
				</td>
				<td>
					<%= link_to t.user.name, user_path(t.user), target: "_blank" %><br />
					<span class='small' ><%= t.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
				</td>
				<td><%= t.position %></td>
				<td><%= render partial:'common/publish', locals:{record: t} %></td>
				<td>
					<%= link_to '查看', t, target: "_blank" %>
					<%= link_to '编辑', edit_tao_path(t), target: "_blank" %>
					<%= link_to '删除', t, method: :delete, data: { confirm: 'Are you sure?' } %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/taos/new.html.erb
<%= form_for @tao ,method: :post, html: {class: 'form-horizontal', multipart: true} do |f|%>
	<div class="form-group">
		<%= f.label :category_id, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.collection_select :category_id, TaoCategory.arrange_as_array({order: 'title'}, @tao_category.possible_parents) , :id, :name_for_selects, include_blank: true, class: "form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :title, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_field :title, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :price, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :price, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :baoyou, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.check_box :baoyou, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :pic, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.file_field :pic, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :url, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :url, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :fanli_url, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :fanli_url, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :desc, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :desc, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :content, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.text_area :content, rows: 4, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :expose_id, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :expose_id, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :position, class: 'col-md-2 control-label' %>
		<div class="col-md-8">
			<%= f.number_field :position, class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/taos/show.html.erb
<p>
  <strong>url:</strong>
  <%= @tao.url %>
</p>

<p>
  <strong>desc:</strong>
  <%= @tao.desc %>
</p>

<p>
  <strong>user_id:</strong>
  <%= @tao.user_id %>
</p>

<%= image_tag @tao.pic.url(:small) %>