config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

	resources :exposes do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :taos do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :tao_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :kus do
		get :list, on: :collection
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :ku_categories do
		put :publish, on: :member
		put :unpublish, on: :member
	end

	resources :pics do
		member do
			put "like", to: "pics#upvote"
			put "dislike", to: "pics#downvote"
			put :publish
			put :unpublish
		end
		get :list, on: :collection
	end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
		<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		</div>
	<% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<ul class="navbar-nav">
	<% if user_signed_in? %>
		<% if current_user.try(:admin?) %>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownManageLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				管理
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdownManageLink">
					<%= link_to '用户', users_path, class: 'dropdown-item' %>
					<%= link_to '爆料', exposes_path, class: 'dropdown-item' %>
					<%= link_to "猴子库分类", ku_categories_path, class: "dropdown-item" %>
					<%= link_to "猴子库", list_kus_path, class: "dropdown-item" %>
					<%= link_to "猴子图", list_pics_path, class: "dropdown-item" %>
					<%= link_to "猴子淘分类", tao_categories_path, class: "dropdown-item" %>
					<%= link_to "猴子淘", list_taos_path, class: "dropdown-item" %>
				</div>
			</li>
		<% end %>
	<% end %>

	<% if user_signed_in? %>
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUserLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<%= current_user.name %>
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdownUserLink">
				<%= link_to '编辑', edit_user_registration_path, class: 'dropdown-item' %>
				<%= link_to '我的爆料', edit_user_registration_path, class: 'dropdown-item' %>
				<%= link_to '我的猴子图', edit_user_registration_path, class: 'dropdown-item' %>
				<%= link_to '登出', destroy_user_session_path, :method=>'delete', class: 'dropdown-item' %>
			</div>
		</li>
	<% else %>
		<li class='nav-item'><%= link_to '登录', new_user_session_path, class: 'nav-link' %></li>
		<li class='nav-item'><%= link_to '注册', new_user_registration_path, class: 'nav-link' %></li>
	<% end %>
</ul>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
	<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		<div class="container">
			<!-- logo -->
			<%= link_to root_path, class: 'navbar-brand' do %>
				<%= image_tag "logo.png", width: 30, height: 30, class: "d-inline-block align-top", alt: "猴子百科" %>
				<span class="logo">猴子百科</span>
			<% end %>
			<!-- 响应式导航 -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<%= render 'layouts/navigation_links' %>
				<%= render 'layouts/nav_links_for_auth' %>
			</div>
		</div>
	</nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!-- <li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li> -->
<ul class="navbar-nav mr-auto">
	<li class="nav-item <%= 'active' if controller_name == 'kus' || controller_name == 'ku_categories' %>">
		<%= link_to "猴子库", kus_path, class: "nav-link" %>
	</li>
	<li class="nav-item <%= 'active' if controller_name == 'pics' %>">
		<%= link_to "猴子图", pics_path, class: "nav-link" %>
	</li>
	<li class="nav-item <%= 'active' if controller_name == 'taos' || controller_name == 'tao_categories' %>">
		<%= link_to "猴子淘", taos_path, class: "nav-link" %>
	</li>
	<li class="nav-item <%= 'active' if controller_name == 'exposes' %>">
		<%= link_to "爆料", new_expose_path, class: "nav-link" %>
	</li>
</ul>
<!-- <form class="form-inline my-2 my-lg-0 mr-auto">
	<input class="form-control form-control-sm mr-sm-2" type="text" placeholder="这里有关于猴子的一切">
	<button class="btn btn-sm btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
</form> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "猴子百科" %></title>
		<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "猴子百科" %>">
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<%= render 'layouts/navigation' %>
		</header>
		<main role="main">
			<%= render 'layouts/messages' %>
			<div class="container">
				<%= yield %>
			</div>
		</main>
	</body>
</html>